apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: 968225077300.dkr.ecr.us-west-1.amazonaws.com/devops-na-nuvem/strimzi/consumer:v3.0
        ports:
        - containerPort: 3000
